[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
